### PR TITLE
[16.0][ADD] l10n_jp_account_report_registration_number

### PR DESCRIPTION
**Pull request by yostashiro**
This module extends external report layouts to show company's Qualified Invoice Issuer
Registration Number on printed invoices and receipts for domestic transactions.

@qrtl

### CODE REVIEW

**Review by kanda999 — APPROVED** [review]
Functional review.

**Review by AungKoKoLin1997 — COMMENTED** [review]
I believe it would benefit us to make this module more generic so that it can be used for other countries by adding an indicator in the res.country. The registration number display would then depend on this indicator. If you agree with this approach, I can create a new PR in the `reporting-engine` repo, building upon the improvements from this current PR.

**Comment by yostashiro** [comment]
@AungKoKoLin1997 As discussed separately, we will keep this PR as is although I wouldn't object to having a generic module in `reporting-engine`.  We are just not sure how much similar needs there are outside Japan.

Can you please review the code.

**Review by AungKoKoLin1997 — APPROVED** [review]

**Pull request merged**
