### PR TITLE
[15.0][MIG] l10n_jp_address_layout: Migration to 15.0

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**

### CODE REVIEW

**Review by kanda999 — CHANGES_REQUESTED** [review]
Complication failed.  Could you confirm this error?　This happened during installation.
2022-10-21_19h10_44

**Comment by AungKoKoLin1997** [comment]
> Complication failed. Could you confirm this error?　This happened during installation. 2022-10-21_19h10_44

I think you need to install node-less.
https://www.odoo.com/forum/help-1/what-does-this-error-mean-on-odoo-could-not-execute-command-lessc-60439?forum=forum.forum%281%2C%29&question=forum.post%2860439%2C%29

**Review by kanda999 — APPROVED** [review]
Function review: It worked as expected.

I installed node-less and created the DB with Japan.

**Review by yostashiro — COMMENTED** [review]
@AungKoKoLin1997 Please squash the migration commits.

**Review by yostashiro — APPROVED** [review]
Thanks!

**Pull request merged**
