### PR TITLE
[MIG]13.0 mig l10n_jp_country_state

### PR DESCRIPTION
**Pull request by TomohiroAbe-Quartile**

### CODE REVIEW

**Comment by yostashiro** [comment]
@TomohiroAbe-Quartile Please follow up on the pre-commit fails.

**Comment by yostashiro** [comment]
@TomohiroAbe-Quartile Please squash your commits (only yours, not the ones from the past) into one for cleaner history (which is a requested practice in OCA).

**Comment by yostashiro** [comment]
@TomohiroAbe-Quartile Also see this for the commit message: https://www.odoo.com/documentation/14.0/developer/reference/guidelines.html#tag-and-module-name

**Comment by TomohiroAbe-Quartile** [comment]
@yostashiro
Sorry, I failed squash command and now history is too complicated.
I close this PR and try again.

**Pull request closed without merging**
