### PR TITLE
16.0[MIG] l10n_jp_partner_title_qweb: Migration to 16.0

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**

### CODE REVIEW

**Review by yostashiro — COMMENTED** [review]
@AungKoKoLin1997 Can you please review this PR https://github.com/OCA/l10n-japan/pull/28 first and then base your migration on that?

**Review by yostashiro — APPROVED** [review]
LGTM. 👍

**Review by kakurai8 — APPROVED** [review]
LGTM.

**Review by kakurai8 — APPROVED** [review]
LGTM

**Pull request merged**
